apiVersion: v2
name: devopshub
description: A Production-Grade Helm Chart for DevOpsHub Cloud-Native Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Shiv Prakash Yadav
    url: https://github.com/shivprakash01
keywords:
  - devops
  - mern
  - kubernetes
  - react
  - nodejs
home: https://github.com/shivprakash01/devopshub
sources:
  - https://github.com/shivprakash01/devopshub
