apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devopshub-server-hpa
  namespace: devopshub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devopshub-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devopshub-client-hpa
  namespace: devopshub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devopshub-client
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
