apiVersion: v1
kind: Secret
metadata:
  name: devopshub-secrets
  namespace: devopshub
  labels:
    app.kubernetes.io/name: devopshub
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://shivpra75_db_user:2cPrMwLyX3BTdVIu@cluster70.frlkkwc.mongodb.net/devopshub?retryWrites=true&w=majority&appName=Cluster70"
