apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-client
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}-client
spec:
  replicas: {{ .Values.replicaCount.client }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
        app.kubernetes.io/name: {{ .Chart.Name }}-client
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}"
          imagePullPolicy: {{ .Values.image.client.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.client.port }}
              name: http
          resources:
            {{- toYaml .Values.resources.client | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: {{ .Values.service.client.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: {{ .Values.service.client.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
