{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-server-hpa
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-server
  minReplicas: {{ .Values.autoscaling.server.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.server.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.server.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.server.targetMemoryUtilizationPercentage }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-client-hpa
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-client
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-client
  minReplicas: {{ .Values.autoscaling.client.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.client.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.client.targetCPUUtilizationPercentage }}
{{- end }}
