apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.server.type }}
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.server.port }}
      targetPort: {{ .Values.service.server.port }}
      name: http
